package com.bootcamp.customer.demo_sb_customer.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.bootcamp.customer.demo_sb_customer.entity.CustomerEntity;

// JPA + Driver (Postgresql)
// ! Hibernate generates the implementation class, which impluments "CustomerRepository"

@Repository //bean
public interface CustomerRepository extends JpaRepository<CustomerEntity, Long> {
  // ! During maven compilation, the implementation class is generated by Hibernate
  //JpaRepository included as follows:  ...因為Hibernate幫手做了
  //save()
  //saveAll()
  //findAll()
  //findById()
  //deleteById()

  
}
