# server.port
server:
  port: 8100

# spring.datasource.driverClassName
# spring.datasource.url
spring.datasource: 
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/bc2412"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

#
api:
  jph:
    domain: "api.coingecko.com"
    endpoints: 
      coinsmarkets: "/api/v3/coins/markets?vs_currency=usd"

